### ISSUE TITLE
Incorrect generated string when translation string ends with colon

### ISSUE THREAD

**Issue by VaidasVisk** [martinlindhe/laravel-vue-i18n-generator#13]
Hello,
I got some empty curly braces in generated string when translation string ends with colon.
For example in translation file:
`Test:`
and I am getting this:
`Test{}`

When this regexp `'/(?<!mailto|tel):\w*/'` in `adjustString` method is changed to `'/(?<!mailto|tel):\w+/'`, it generates normal string `Test:` as expected.

**Comment by martinlindhe** [comment]
Thanks for the report, and I'll look into improving the regex with your test data.

However, it might be wise to exclude the ":" part from your translation strings, because it has special meaning in Laravel, see https://laravel.com/docs/5.4/localization#replacing-parameters-in-translation-strings

Also, so you don't end up needing multiple strings for "Test:", "Test", etc

**Comment by VaidasVisk** [comment]
Yeah, I did that by mistake and when I noticed that, I just reported here. :)
And I know that Laravel's translation strings can have attributes prefixed with colon (`:`), but... In this case there is no text after colon, but in Laravel's translator **must** be text after colon. [https://github.com/laravel/.../Illuminate/Translation/Translator.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Translation/Translator.php#L264).
