### ISSUE TITLE
Cannot use : in text

### ISSUE THREAD

**Issue by SemBakkum** [martinlindhe/laravel-vue-i18n-generator#14]
I’m trying to add : in a string as just plain text but the converter sees it as a variable and converts it to {}. Is there some way to only convert : with a variable name like ':name'.

**Comment by martinlindhe** [comment]
Hm, I thought we fixed such bug not too long ago, in commit https://github.com/martinlindhe/laravel-vue-i18n-generator/commit/e93134b266e97eb39a7e2887ce881fe97ac11c33

Are you using the latest version? The fix is included in 0.1.12

Either way, since ":" is not language, you can solve this by not trying to translate this.

**Comment by martinlindhe** [comment]
@SemBakkum Did you resolve this issue?

**Comment by SemBakkum** [comment]
@martinlindhe Yes we did, quite easily to be honest. We're using the colon html number and importing it as HTML with VueJS.
