### ISSUE TITLE
Problem with colon in translate text

### ISSUE THREAD

**Issue by lwadas** [martinlindhe/laravel-vue-i18n-generator#69]
Hi,

I have a problem when try generate translation for VUE.

In source language file i have:
```
 'description' => 'Przesyłka kurierska z doręczeniem do godziny 10:00 następnego dnia.'
```
when i use php artisan vue-i18n:generate

then get:
```
  "description": "Przesyłka kurierska z doręczeniem do godziny 10{00} następnego dnia."
```
why is there no escape char to skip the selected colon?

**Comment by martinlindhe** [comment]
> why is there no escape char to skip the selected colon?

The issue has not popped up before.
It makes sense to allow a escape char to skip the colon. If you are interested in working on this let me know. Otherwise it will happen soonish.

As a work-around for now, you can use a unicode version of the colon symbol.
Here's a list: https://unicode-search.net/unicode-namesearch.pl?term=COLON

Some examples:

ː MO­DI­FI­ER LET­TER TRIANGULAR COLON
˸ MO­DI­FI­ER LET­TER RAISED COLON
